# Ruff Global settings
fix = false # for now
builtins = ["_"]
show-fixes = true
line-length = 100
indent-width = 4
target-version = "py39"
extend-exclude = [
  ".run", ".idea", ".github", "__pycache__",
]

[format]
quote-style = "double"
docstring-code-format = true

[lint]
select = ["ALL"]

# Ignore overly strict or stylistic docstring rules
ignore = [
  "B013",    # Allow One length tuple in the exception handlers
  "D100",    # Missing docstring in public modules
  "D104",    # Missing docstring in public packages
  "D105",    # Missing docstring in magic methods
  "D107",    # Missing docstring in __init__
  "D203",    # 1 blank line required before class docstring
  "D212",    # Multi-line docstring summary should start at the first line
  "D213",    # Multi-line docstring summary should start at the second line
  "D401",    # The first line should be in imperative mode
  "D404",    # The First word of docstring should not be "This"
  "D405",    # Section name should be properly capitalized
  "D406",    # The section name should end with a newline
  "D407",    # Missing dashed underline after section
  "D408",    # Section underline is too short
  "D409",    # Section underline is too long
  "D410",    # Missing blank line after a section
  "D411",    # Missing blank line before a section
  "D413",    # Missing blank line after the last section
  "N812",    # Allow lowercase imports to be aliased as non-lowercase
  "N802",    # Allow mixed case function name
  "N803",    # Allow mixed case variable name in function argumets
  "N8",      # Aloow all naming violations
  "ANN",     # Allow all missing annotations
  "ERA001",  # Keep commented out codes, linter hack: write comments docstring
  "T201",    # Allow print statements
  "T203",    # Allow pprint statements
  "Q000",    # Allow single quotes
  "F401",    # Keep unused imports **for now**
  "F841",    # Allow unused variables **for now**
  "ANN204",  # Docstring missing in special __dunder__ method
  "COM812",  # Missing trailing comma in a multi-line collection
  "Q000",    # Allow quotation violation
  "Q003",    # Allow quotation violation
  "S104",    # Allow binding to all interfaces (0.0.0.0)
  "PERF401", # Ignore suggestion to use `extend` to create a transformed list,
  "INP001",  # Ignore implcit namespace package
]

[lint.flake8-annotations]
allow-star-arg-any = true     # Allow `*args: Any` and `**kwargs: Any`

[lint.isort]
length-sort = true
combine-as-imports = true
force-single-line = false
known-first-party = ["upwork_cli"]
